@startuml

title Fonctionnement de l'application


(*) --> "Connection à l'application web"
--> "Chargement de l'environnement 3D"
--> "Chargement des ciseaux"
-->"Créer joueur"

if"Appuie sur les touches (zqsd)" then
-->[alors]"Joueur ce deplace dans l'environnement"

if"Joueur ce deplace vers une plaque"then
-->[alors]"Essaye de couper la plaque"
-->"Reçois un retour de force avec le ciseaux physique"
-->(*)

else

-->[sinon]"Faire bouger les ciseaux physiquement"
endif
else
-->[sinon]"Le joueur reste immobile"
-->"Faire bouger les ciseaux physiquement"
endif

-->"Ciseaux virtuel suivent le mouvement"
-->(*)