@startuml

title Fonctionnement de l'application


(*) --> "Connection à l'application web"
--> "Chargement de l'environnement 3D"
--> "Creation des mains"
--> "Connexion au gant"

if "Collision entre l'index et le cube" then
    -->[alors]"Retour de force sur l'index"
else
    --> [sinon] "pas de retour de force sur le pouce"
    if "Collision entre le pouce et le cube" then
        -->[alors]"Retour de force sur le pouce"
        else
            --> [sinon] "pas de retour de force sur le pouce"
        endif
endif

-->"Ciseaux virtuel suivent le mouvement"
-->(*)