@startuml BDD_diag
title Diagramme BDD

class Plaque {
    id: int
    position: Vector3
    rotation: Quaternion
    durete: int
    temps: int
    textureDiffuse: String
    textureNormal: String
    textureRoughness: String
}

class Modele {
    id: int
    position: Vector3
    rotation: Quaternion
    lien: String
}

@enduml