@startuml
title Fonctionnement de la Base de donnee\n exemple de recuperation de la position de la plaque 1

participant PageWeb as web
participant Serveur as serv
participant "LecteurJSON" as bdd

activate web
    web -> serv : getResource(["Plaques", "1", "position"])
    activate serv
        serv -> bdd : lireFichier(["Plaques", "1", "position"])
        activate bdd
            bdd -> json : lecture()
            activate json
            json -> bdd : information
            deactivate json
        bdd -> serv : position
        deactivate bdd
    serv -> web : position
    deactivate serv
deactivate web

@enduml